---
# detect skipping due to no matching hosts found issue
- name: Create a file to signal the playbook ran
  file:
    path: run_check
    state: touch

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: Increase file descriptor limit for root
  pam_limits:
    domain: 'root'
    limit_type: '-'
    limit_item: nofile
    value: "{{ fd_limit }}"

- name: Increase file descriptor limit for ubuntu
  pam_limits:
    domain: 'ubuntu'
    limit_type: 'soft'
    limit_item: nofile
    value: "{{ fd_limit }}"

- name: Enable pam_limits.so
  lineinfile:
    path: /etc/pam.d/common-session
    insertafter: EOF
    line: 'session required pam_limits.so'

- name: Ensure the locale exists
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: set as default locale
  command: update-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8

- name: Reboot the machine with all defaults
  reboot:
    
- name: Update all packages
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: true

# - name: Install Python
#   apt:
#     name: python
#     update_cache: yes
#     install_recommends: yes
#     state: present
    
- name: get name of second volume
  shell: "lsblk | grep {{ volume_size_label }} | cut -d' ' -f1"
  register: volume_name

- name: Create a filesystem on extra EBS volume
  filesystem:
    fstype: "{{ filesystem }}"
    dev: "/dev/{{ volume_name.stdout }}"

- name: create rabbitmq directory
  file: 
    path: /rabbitmq 
    state: directory 
    owner: ubuntu 
    group: ubuntu
  become: true

- name: Mount EBS volume for rabbitmq directory
  mount:
    path: /rabbitmq
    src: "/dev/{{ volume_name.stdout }}"
    fstype: "{{ filesystem }}"
    state: mounted

- name: get UUID of RabbitMQ mount volume
  shell: blkid -s UUID -o value $( df /rabbitmq )
  register: rabbitmq_uuid
  become: true

- name: Convert fstab device name to UUID format
  replace:
    dest=/etc/fstab
    regexp="/dev/{{ volume_name.stdout }}"
    replace="UUID={{rabbitmq_uuid.stdout}}"
    backup=yes

- name: create rabbitmq log directory
  file: 
    path: /rabbitmq/log
    state: directory 
    owner: ubuntu 
    group: ubuntu
  become: true

- name: create rabbitmq data directory
  file: 
    path: /rabbitmq/data
    state: directory 
    owner: ubuntu 
    group: ubuntu
  become: true